spring:
  application:
    name: unicorn

  #database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/suhrob
    username: suhrob
    password: 123

  #jpa
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  #liquibase

  #server
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
server:
  port: 8082

services:
  s3:
    endpoint: http://localhost:9000
    minio-host: https://localhost:9000
    access-key: user
    secret-key: password
    bucket-name: user-project
    region: us-east-1